#!/bin/bash

function install_gui() {
    if [ $1 == "mate" ]; then
        echo "Installing MATE"
        sleep 1;

        echo "Installing X window system"
        pacman -S --noconfirm xorg xorg-server
        sleep 1;

        echo "Installing MATE Desktop Environment (migth take some time)"
        pacman -S --noconfirm mate mate-extra

        echo "Installing LightDM"
        pacman -S --noconfirm lightdm"
        pacman -S lightdm-gtk-greeter
        systemctl enable lightdm
    fi
}
