#!/bin/bash

source "$(dirname "$0")/utils"
source "$(dirname "$0")/network"

settings=("keybord_layout" "font" "browser" "extensions" "gui")

# Intro: ------------------------------------------------------------------------------------------
printf '\e[36m
      ▗▄▖  ▄▄▄ ▗▞▀▘▐▌             
     ▐▌ ▐▌█    ▐▌  ▐▌             
     ▐▛▀▜▌█    ▝▚▄▖▐▛▀▚▖          
     ▐▌ ▐▌         ▐▌ ▐▌          \e[35m
 ———————[by A-Allaz]——————— \e[36m
  ▗▄▄▖▄▄▄  ▄▄▄▄  ▗▞▀▀▘▄ ▗▄▖ 
 ▐▌  █   █ █   █ ▐▌   ▄▐▌ ▐▌
 ▐▌  ▀▄▄▄▀ █   █ ▐▛▀▘ █ ▝▀▜▌
 ▝▚▄▄▖           ▐▌   █▐▙▄▞▘\e[35m
Available at:        
https://github.com/A-Allaz/Arch-Config \e[0m
\n'

sleep 1;

# Wifi setup: -------------------------------------------------------------------------------------
select_network

# Username: ---------------------------------------------------------------------------------------

# Root Password: ----------------------------------------------------------------------------------

# Keyboard layout: --------------------------------------------------------------------------------
localectl list-x11-keymap-layouts | grep -E "us|fr|de" > /tmp/layouts
IFS=$'\n' read -r -d '' -a layouts < /tmp/layouts

select_option "${layouts[@]}"
selected_keybord_layout="${layouts[$?]}"

# Font: -------------------------------------------------------------------------------------------
fc-list : family | sort | uniq | grep -v 'Noto' > /tmp/fonts
IFS=$'\n' read -r -d '' -a fonts < /tmp/fonts

select_option "${fonts[@]}"
selected_font="${fonts[$?]}"

# Browser: ----------------------------------------------------------------------------------------
browsers=("firefox" "brave" "chromium")

select_option "${browsers[@]}"
selected_browser="${browsers[$?]}"

# Extensions: -------------------------------------------------------------------------------------

# Grphical User Interface: ------------------------------------------------------------------------

# Recap: ------------------------------------------------------------------------------------------
echo "selected settings:"
for i in $(seq 1 ${#settings[@]}); 
do
      selected_value="selected_${settings[i - 1]}"
      echo -e "$i\t${settings[i - 1]}: $selected_value"
      sleep 0.5
done

# Apply selection: --------------------------------------------------------------------------------
echo Applying keyboard layout: $selected_keybord_layout
#localectl set-keymap --no-conv $selected_keybord_layout
sleep 1;


