#!/bin/bash

source "$(dirname "$0")/utils"

# Intro: ------------------------------------------------------------------------------------------
printf '\e[36m
      ▗▄▖  ▄▄▄ ▗▞▀▘▐▌             
     ▐▌ ▐▌█    ▐▌  ▐▌             
     ▐▛▀▜▌█    ▝▚▄▖▐▛▀▚▖          
     ▐▌ ▐▌         ▐▌ ▐▌          \e[35m
 ———————[by A-Allaz]——————— \e[36m
  ▗▄▄▖▄▄▄  ▄▄▄▄  ▗▞▀▀▘▄ ▗▄▖ 
 ▐▌  █   █ █   █ ▐▌   ▄▐▌ ▐▌
 ▐▌  ▀▄▄▄▀ █   █ ▐▛▀▘ █ ▝▀▜▌
 ▝▚▄▄▖           ▐▌   █▐▙▄▞▘\e[35m
Available at:        
https://github.com/A-Allaz/Arch-Config \e[0m
\n'

sleep 1;

# Select keyboard layout: -------------------------------------------------------------------------
printf ""

localectl list-x11-keymap-layouts | grep -E "us|fr|de" > /tmp/layouts
IFS=$'\n' read -r -d '' -a layouts < /tmp/layouts

selected_layout=select_option "${layouts[@]}"

# Select font: ------------------------------------------------------------------------------------
fc-list : family | sort | uniq | grep -v 'Noto' > /tmp/fonts
IFS=$'\n' read -r -d '' -a fonts < /tmp/fonts

selected_font=select_option "${fonts[@]}"

# Wifi setup

# Apply selection: --------------------------------------------------------------------------------
echo Applying keyboard layout: $selected_layout
localectl set-keymap --no-conv $selected_layout
sleep 1;


