#!/bin/bash

source "$(dirname "$0")/utils"

settings=(keybord_layout font browser extensions)

# Intro: ------------------------------------------------------------------------------------------
printf '\e[36m
      ▗▄▖  ▄▄▄ ▗▞▀▘▐▌             
     ▐▌ ▐▌█    ▐▌  ▐▌             
     ▐▛▀▜▌█    ▝▚▄▖▐▛▀▚▖          
     ▐▌ ▐▌         ▐▌ ▐▌          \e[35m
 ———————[by A-Allaz]——————— \e[36m
  ▗▄▄▖▄▄▄  ▄▄▄▄  ▗▞▀▀▘▄ ▗▄▖ 
 ▐▌  █   █ █   █ ▐▌   ▄▐▌ ▐▌
 ▐▌  ▀▄▄▄▀ █   █ ▐▛▀▘ █ ▝▀▜▌
 ▝▚▄▄▖           ▐▌   █▐▙▄▞▘\e[35m
Available at:        
https://github.com/A-Allaz/Arch-Config \e[0m
\n'

sleep 1;

# Wifi setup: -------------------------------------------------------------------------------------

# Username: ---------------------------------------------------------------------------------------

# Root Password: ----------------------------------------------------------------------------------

# Keyboard layout: --------------------------------------------------------------------------------
printf ""

localectl list-x11-keymap-layouts | grep -E "us|fr|de" > /tmp/layouts
IFS=$'\n' read -r -d '' -a layouts < /tmp/layouts

selected_keybord_layout=select_option "${layouts[@]}"

# Font: -------------------------------------------------------------------------------------------
fc-list : family | sort | uniq | grep -v 'Noto' > /tmp/fonts
IFS=$'\n' read -r -d '' -a fonts < /tmp/fonts

selected_font=select_option "${fonts[@]}"

# Browser: ----------------------------------------------------------------------------------------
browsers=("firefox" "brave" "chromium")

selected_browser=select_option "${browsers[@]}"

# Extensions: -------------------------------------------------------------------------------------

# Recap: ------------------------------------------------------------------------------------------
echo "selected settings:"
for i in $(seq 1 ${#settings[@]}); 
do
      selected_value="selected_${settings[i - 1]}"
      echo -e "$i\t${settings[i - 1]}: $selected_value"
      sleep 0.5
done

# Apply selection: --------------------------------------------------------------------------------
echo Applying keyboard layout: $selected_keybord_layout
localectl set-keymap --no-conv $selected_keybord_layout
sleep 1;


